name: "Setup Node environment"
description: "Setup node and yarn environment"

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 24

    - name: Corepack
      working-directory: ./data/web
      shell: bash
      run: corepack enable

    - name: Cache paths for Yarn
      id: cache-folder
      shell: bash
      run: |
        echo "cache-folder=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

    - name: Cache install-state
      uses: actions/cache@v5
      with:
        path: |
          ${{ steps.cache-folder.outputs.cache-folder }}
          data/web/.yarn/install-state.gz
          data/web/node_modules
        key: node-cache-${{ runner.os }}-${{ hashFiles('data/web/yarn.lock') }}
        restore-keys: |
          node-cache-${{ runner.os }}-

    - name: Tools versions
      working-directory: ./data/web
      shell: bash
      run: |
        node --version
        yarn --version

    - name: Install modules
      working-directory: ./data/web
      shell: bash
      run: yarn install
