extensions:
  - proj_flow.ext.cplusplus
  - proj_flow.ext.github
  - proj_flow.ext.sign
  - proj_flow.ext.store
  - proj_flow.ext.test_runner
  - proj_flow.ext.tools
  - proj_flow.ext.tests
  - proj_flow.ext.webidl
  - proj_flow.minimal.ext.bug_report
  - quick_dra.icons
  - quick_dra.yaml_reader
  - quick_dra.qtest2junit
  - quick_dra.image_errors
  - proj_flow_test_coverage.ext

entry:
  config: [Conan, CMake]
  build: [Build]
  test: [Build, Test]
  test-report: [QTestToJUnit, JUnitToCtrf, MergeCtrfFiles]
  verify:
    - Build
    - Test
    - Sign
    - Pack
    - SignPackages
    - Store
    - BinInst
    - DevInst

run-env.Test:
  LC_ALL: pl_PL.UTF-8

compiler:
  names:
    gcc: [gcc, g++]
  os-default: { ubuntu: gcc, windows: msvc }

lts:
  windows: [windows-2022]

postproc:
  exclude:
    - { github_os: ubuntu-24.04, sanitizer: true }
    - { github_os: ubuntu-26.04, sanitizer: true }
  include:
    - { os: ubuntu, gcc_ver: 13 }
    - { github_os: ubuntu-24.04, gcc_ver: 14 }
    - { github_os: ubuntu-26.04, gcc_ver: 15 }

cmake:
  vars:
    QUICK_DRA_SANITIZE: "?config:sanitizer"
    QUICK_DRA_COVERALLS: "?config:coverage"
    QUICK_DRA_COVERALLS_UPLOAD: "?config:upload_to_coveralls"
    QUICK_DRA_W_ERROR: "?config:w-error"
    QUICK_DRA_WIN_GUI_CONSOLE: "?config:win-console"

package:
  main-group: apps

shortcuts:
  dbg: { build_type: Debug, sanitizer: false }
  rel: { build_type: Release, sanitizer: false }
  both: { build_type: [Debug, Release], sanitizer: false }
  sane: { build_type: Debug, sanitizer: true }

test:
  target: QUICK_DRA_coveralls
  junit-dir: test-results/junit-test
  ctrf-dir: test-results/ctrf
  ctrf-report: ../artifacts/test-results/ctrf.json

test-runner:
  target: qdra
  report_env: QDRA_
  install: [C001_cli, C004_data]
  testsuite:
    root: libs/cli/tests
    data: data
    default-set: core
  patches: {}

image-errors:
  tests/controls-test: libs/gui/controls/tests/images
  tests/gui-6-test: libs/gui/gui/tests/qt6/images
