// Copyright (c) 2026 Marcin Zdun
// This code is licensed under MIT license (see LICENSE for details)
// This file is auto-generated. To recreate, call
//
//     python tools/webapp-vfs.py
//

#include <array>
#include <quick_dra/gui/vfs.hpp>

using namespace std::literals;

namespace quick_dra::gui {
	namespace contents {
		static constexpr auto file_favicon_svg =
		    "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<svg width=\"32px\" height=\"32px\" version=\"1.1\" viewBox="
		    "\"-18.5 -43.144 147 147\"\n    xmlns=\"http://www.w3.org/2000/svg\" fill=\"#00923f\">\n    <path\n       "
		    " d=\"m110.71-25.153c-1.9095-0.05868-4.0416 0.03972-6.4183 0.32662-26.285 3.173-31.995 1.3462-58.898 4.163"
		    "4-5.6045 0.58686-19.846 1.3552-29.067 3.5906-7.6143 1.846-16.241 3.7107-21.7 11.097-6.386 8.6393-11.32 22"
		    ".252-9.5331 34.253 5.1973 34.901 15.706 7.7408 83.721 64.533 3.0085 3.1362 8.3398-0.91155 10.16-5.0852-44"
		    ".337-48.531-43.644-33.453-42.078-60.327 0.5326-9.1416 10.027-16.589 32.989-23.156 14.421-4.1241 54.806-14"
		    ".998 54.806-14.998 1.7914-5.8287-0.6145-13.987-13.981-14.398zm10.879 22.949-14.687 4.9578s3.0013-0.17434 "
		    "7.5149 13.155c4.5136 13.329 7.1724 27.42 7.1724 27.42s2.7112-8.8888 2.5705-26.44c-0.14074-17.552-2.5705-1"
		    "9.093-2.5705-19.093zm-24.996 3.8451-14.687 4.9578s3.0014-0.1743 7.515 13.155c4.5136 13.329 7.1724 27.42 7"
		    ".1724 27.42s2.7112-8.8862 2.5705-26.438c-0.14074-17.552-2.5705-19.095-2.5705-19.095zm-49.163 41.051s21.3 "
		    "15.12 39.906 32.702c12.602 11.908 15.466 17.937 16.007 20.596-0.12958-3.0958-1.0776-9.9023-6.4501-17.412-"
		    "7.3075-10.214-13.068-14.799-13.068-14.799s7.2069 1.4653 22.919 11.559c15.712 10.094 15.736 16.783 15.736 "
		    "16.783s-0.26263-19.806-29.245-33.446c-28.982-13.64-45.807-15.983-45.807-15.983zm55.913 53.298c0.0465 1.11"
		    "5-4e-3 1.7765-4e-3 1.7765s0.26301-0.50965 4e-3 -1.7765z\"\n        stroke-width=\"2.4985\" style=\"paint-"
		    "order:markers stroke fill\" />\n</svg>"
		    ""sv;

		static constexpr auto file_index_html =
		    "<!doctype html><html lang=\"en\"><head><title></title><meta charset=\"utf-8\"><meta name=\"viewport\" con"
		    "tent=\"width=device-width,initial-scale=1,viewport-fit=cover\"><meta name=\"Description\" content=\"Put y"
		    "our description here.\"><script src=\"webui.js\"></script><base href=\"/\"><style>*{margin:0;padding:0;bo"
		    "x-sizing:border-box}body{font-family:'Segoe UI',Roboto,Helvetica,Arial,sans-serif;overflow:hidden;backgro"
		    "und-color:transparent;width:100vw;height:100vh;display:flex}</style><title>quick-dra</title></head><body>"
		    "<script type=\"module\" src=\"./index.js\" onerror=\"setTimeout(()=>{window.location.reload()},1e3)\"></s"
		    "cript><script inject-service-worker=\"\">\"serviceWorker\"in navigator&&window.addEventListener(\"load\","
		    "function(){navigator.serviceWorker.register(\"sw.js\").then(function(){console.log('ServiceWorker registe"
		    "red from \"sw.js\".')}).catch(function(e){console.log(\"ServiceWorker registration failed: \",e)})})</scr"
		    "ipt></body></html>"
		    ""sv;

		static constexpr auto file_index_js =
		    "var zt,Dt,jt,It,Bt,qt;function T(s,t,e,o){var r=arguments.length,n=r<3?t:o===null?o=Object.getOwnProperty"
		    "Descriptor(t,e):o,i;if(typeof Reflect==\"object\"&&typeof Reflect.decorate==\"function\")n=Reflect.decora"
		    "te(s,t,e,o);else for(var a=s.length-1;a>=0;a--)(i=s[a])&&(n=(r<3?i(n):r>3?i(t,e,n):i(t,e))||n);return r>3"
		    "&&n&&Object.defineProperty(t,e,n),n}function U(s,t,e,o){if(e===\"a\"&&!o)throw new TypeError(\"Private ac"
		    "cessor was defined without a getter\");if(typeof t==\"function\"?s!==t||!o:!t.has(s))throw new TypeError("
		    "\"Cannot read private member from an object whose class did not declare it\");return e===\"m\"?o:e===\"a"
		    "\"?o.call(s):o?o.value:t.get(s)}typeof SuppressedError==\"function\"&&SuppressedError;/**\n * @license\n "
		    "* Copyright 2019 Google LLC\n * SPDX-License-Identifier: BSD-3-Clause\n */const D=globalThis,J=D.ShadowRo"
		    "ot&&(D.ShadyCSS===void 0||D.ShadyCSS.nativeShadow)&&\"adoptedStyleSheets\"in Document.prototype&&\"replac"
		    "e\"in CSSStyleSheet.prototype,K=Symbol(),ft=new WeakMap;let $t=class{constructor(t,e,o){if(this._$cssResu"
		    "lt$=!0,o!==K)throw Error(\"CSSResult is not constructable. Use `unsafeCSS` or `css` instead.\");this.cssT"
		    "ext=t,this.t=e}get styleSheet(){let t=this.o;const e=this.t;if(J&&t===void 0){const o=e!==void 0&&e.lengt"
		    "h===1;o&&(t=ft.get(e)),t===void 0&&((this.o=t=new CSSStyleSheet).replaceSync(this.cssText),o&&ft.set(e,t)"
		    ")}return t}toString(){return this.cssText}};const Wt=s=>new $t(typeof s==\"string\"?s:s+\"\",void 0,K),j="
		    "(s,...t)=>{const e=s.length===1?s[0]:t.reduce((o,r,n)=>o+(i=>{if(i._$cssResult$===!0)return i.cssText;if("
		    "typeof i==\"number\")return i;throw Error(\"Value passed to 'css' function must be a 'css' function resul"
		    "t: \"+i+\". Use 'unsafeCSS' to pass non-literal values, but take care to ensure page security.\")})(r)+s["
		    "n+1],s[0]);return new $t(e,s,K)},Vt=(s,t)=>{if(J)s.adoptedStyleSheets=t.map(e=>e instanceof CSSStyleSheet"
		    "?e:e.styleSheet);else for(const e of t){const o=document.createElement(\"style\"),r=D.litNonce;r!==void 0"
		    "&&o.setAttribute(\"nonce\",r),o.textContent=e.cssText,s.appendChild(o)}},gt=J?s=>s:s=>s instanceof CSSSty"
		    "leSheet?(t=>{let e=\"\";for(const o of t.cssRules)e+=o.cssText;return Wt(e)})(s):s;/**\n * @license\n * C"
		    "opyright 2017 Google LLC\n * SPDX-License-Identifier: BSD-3-Clause\n */const{is:Qt,defineProperty:Zt,getO"
		    "wnPropertyDescriptor:Ft,getOwnPropertyNames:Gt,getOwnPropertySymbols:Jt,getPrototypeOf:Kt}=Object,g=globa"
		    "lThis,vt=g.trustedTypes,Xt=vt?vt.emptyScript:\"\",X=g.reactiveElementPolyfillSupport,M=(s,t)=>s,I={toAttr"
		    "ibute(s,t){switch(t){case Boolean:s=s?Xt:null;break;case Object:case Array:s=s==null?s:JSON.stringify(s)}"
		    "return s},fromAttribute(s,t){let e=s;switch(t){case Boolean:e=s!==null;break;case Number:e=s===null?null:"
		    "Number(s);break;case Object:case Array:try{e=JSON.parse(s)}catch(o){e=null}}return e}},Y=(s,t)=>!Qt(s,t),"
		    "mt={attribute:!0,type:String,converter:I,reflect:!1,useDefault:!1,hasChanged:Y};(zt=Symbol.metadata)!=nul"
		    "l||(Symbol.metadata=Symbol(\"metadata\")),(Dt=g.litPropertyMetadata)!=null||(g.litPropertyMetadata=new We"
		    "akMap);let x=class extends HTMLElement{static addInitializer(t){var e;this._$Ei(),((e=this.l)!=null?e:thi"
		    "s.l=[]).push(t)}static get observedAttributes(){return this.finalize(),this._$Eh&&[...this._$Eh.keys()]}s"
		    "tatic createProperty(t,e=mt){if(e.state&&(e.attribute=!1),this._$Ei(),this.prototype.hasOwnProperty(t)&&("
		    "(e=Object.create(e)).wrapped=!0),this.elementProperties.set(t,e),!e.noAccessor){const o=Symbol(),r=this.g"
		    "etPropertyDescriptor(t,o,e);r!==void 0&&Zt(this.prototype,t,r)}}static getPropertyDescriptor(t,e,o){var i"
		    ";const{get:r,set:n}=(i=Ft(this.prototype,t))!=null?i:{get(){return this[e]},set(a){this[e]=a}};return{get"
		    ":r,set(a){const l=r==null?void 0:r.call(this);n==null||n.call(this,a),this.requestUpdate(t,l,o)},configur"
		    "able:!0,enumerable:!0}}static getPropertyOptions(t){var e;return(e=this.elementProperties.get(t))!=null?e"
		    ":mt}static _$Ei(){if(this.hasOwnProperty(M(\"elementProperties\")))return;const t=Kt(this);t.finalize(),t"
		    ".l!==void 0&&(this.l=[...t.l]),this.elementProperties=new Map(t.elementProperties)}static finalize(){if(t"
		    "his.hasOwnProperty(M(\"finalized\")))return;if(this.finalized=!0,this._$Ei(),this.hasOwnProperty(M(\"prop"
		    "erties\"))){const e=this.properties,o=[...Gt(e),...Jt(e)];for(const r of o)this.createProperty(r,e[r])}co"
		    "nst t=this[Symbol.metadata];if(t!==null){const e=litPropertyMetadata.get(t);if(e!==void 0)for(const[o,r]o"
		    "f e)this.elementProperties.set(o,r)}this._$Eh=new Map;for(const[e,o]of this.elementProperties){const r=th"
		    "is._$Eu(e,o);r!==void 0&&this._$Eh.set(r,e)}this.elementStyles=this.finalizeStyles(this.styles)}static fi"
		    "nalizeStyles(t){const e=[];if(Array.isArray(t)){const o=new Set(t.flat(1/0).reverse());for(const r of o)e"
		    ".unshift(gt(r))}else t!==void 0&&e.push(gt(t));return e}static _$Eu(t,e){const o=e.attribute;return o===!"
		    "1?void 0:typeof o==\"string\"?o:typeof t==\"string\"?t.toLowerCase():void 0}constructor(){super(),this._$"
		    "Ep=void 0,this.isUpdatePending=!1,this.hasUpdated=!1,this._$Em=null,this._$Ev()}_$Ev(){var t;this._$ES=ne"
		    "w Promise(e=>this.enableUpdating=e),this._$AL=new Map,this._$E_(),this.requestUpdate(),(t=this.constructo"
		    "r.l)==null||t.forEach(e=>e(this))}addController(t){var e,o;((e=this._$EO)!=null?e:this._$EO=new Set).add("
		    "t),this.renderRoot!==void 0&&this.isConnected&&((o=t.hostConnected)==null||o.call(t))}removeController(t)"
		    "{var e;(e=this._$EO)==null||e.delete(t)}_$E_(){const t=new Map,e=this.constructor.elementProperties;for(c"
		    "onst o of e.keys())this.hasOwnProperty(o)&&(t.set(o,this[o]),delete this[o]);t.size>0&&(this._$Ep=t)}crea"
		    "teRenderRoot(){var e;const t=(e=this.shadowRoot)!=null?e:this.attachShadow(this.constructor.shadowRootOpt"
		    "ions);return Vt(t,this.constructor.elementStyles),t}connectedCallback(){var t,e;(t=this.renderRoot)!=null"
		    "||(this.renderRoot=this.createRenderRoot()),this.enableUpdating(!0),(e=this._$EO)==null||e.forEach(o=>{va"
		    "r r;return(r=o.hostConnected)==null?void 0:r.call(o)})}enableUpdating(t){}disconnectedCallback(){var t;(t"
		    "=this._$EO)==null||t.forEach(e=>{var o;return(o=e.hostDisconnected)==null?void 0:o.call(e)})}attributeCha"
		    "ngedCallback(t,e,o){this._$AK(t,o)}_$ET(t,e){var n;const o=this.constructor.elementProperties.get(t),r=th"
		    "is.constructor._$Eu(t,o);if(r!==void 0&&o.reflect===!0){const i=(((n=o.converter)==null?void 0:n.toAttrib"
		    "ute)!==void 0?o.converter:I).toAttribute(e,o.type);this._$Em=t,i==null?this.removeAttribute(r):this.setAt"
		    "tribute(r,i),this._$Em=null}}_$AK(t,e){var n,i,a;const o=this.constructor,r=o._$Eh.get(t);if(r!==void 0&&"
		    "this._$Em!==r){const l=o.getPropertyOptions(r),h=typeof l.converter==\"function\"?{fromAttribute:l.conver"
		    "ter}:((n=l.converter)==null?void 0:n.fromAttribute)!==void 0?l.converter:I;this._$Em=r;const u=h.fromAttr"
		    "ibute(e,l.type);this[r]=(a=u!=null?u:(i=this._$Ej)==null?void 0:i.get(r))!=null?a:u,this._$Em=null}}reque"
		    "stUpdate(t,e,o,r=!1,n){var i,a;if(t!==void 0){const l=this.constructor;if(r===!1&&(n=this[t]),o!=null||(o"
		    "=l.getPropertyOptions(t)),!(((i=o.hasChanged)!=null?i:Y)(n,e)||o.useDefault&&o.reflect&&n===((a=this._$Ej"
		    ")==null?void 0:a.get(t))&&!this.hasAttribute(l._$Eu(t,o))))return;this.C(t,e,o)}this.isUpdatePending===!1"
		    "&&(this._$ES=this._$EP())}C(t,e,{useDefault:o,reflect:r,wrapped:n},i){var a,l,h;o&&!((a=this._$Ej)!=null?"
		    "a:this._$Ej=new Map).has(t)&&(this._$Ej.set(t,(l=i!=null?i:e)!=null?l:this[t]),n!==!0||i!==void 0)||(this"
		    "._$AL.has(t)||(this.hasUpdated||o||(e=void 0),this._$AL.set(t,e)),r===!0&&this._$Em!==t&&((h=this._$Eq)!="
		    "null?h:this._$Eq=new Set).add(t))}async _$EP(){this.isUpdatePending=!0;try{await this._$ES}catch(e){Promi"
		    "se.reject(e)}const t=this.scheduleUpdate();return t!=null&&await t,!this.isUpdatePending}scheduleUpdate()"
		    "{return this.performUpdate()}performUpdate(){var o,r;if(!this.isUpdatePending)return;if(!this.hasUpdated)"
		    "{if((o=this.renderRoot)!=null||(this.renderRoot=this.createRenderRoot()),this._$Ep){for(const[i,a]of this"
		    "._$Ep)this[i]=a;this._$Ep=void 0}const n=this.constructor.elementProperties;if(n.size>0)for(const[i,a]of "
		    "n){const{wrapped:l}=a,h=this[i];l!==!0||this._$AL.has(i)||h===void 0||this.C(i,void 0,a,h)}}let t=!1;cons"
		    "t e=this._$AL;try{t=this.shouldUpdate(e),t?(this.willUpdate(e),(r=this._$EO)==null||r.forEach(n=>{var i;r"
		    "eturn(i=n.hostUpdate)==null?void 0:i.call(n)}),this.update(e)):this._$EM()}catch(n){throw t=!1,this._$EM("
		    "),n}t&&this._$AE(e)}willUpdate(t){}_$AE(t){var e;(e=this._$EO)==null||e.forEach(o=>{var r;return(r=o.host"
		    "Updated)==null?void 0:r.call(o)}),this.hasUpdated||(this.hasUpdated=!0,this.firstUpdated(t)),this.updated"
		    "(t)}_$EM(){this._$AL=new Map,this.isUpdatePending=!1}get updateComplete(){return this.getUpdateComplete()"
		    "}getUpdateComplete(){return this._$ES}shouldUpdate(t){return!0}update(t){this._$Eq&&(this._$Eq=this._$Eq."
		    "forEach(e=>this._$ET(e,this[e]))),this._$EM()}updated(t){}firstUpdated(t){}};x.elementStyles=[],x.shadowR"
		    "ootOptions={mode:\"open\"},x[M(\"elementProperties\")]=new Map,x[M(\"finalized\")]=new Map,X==null||X({Re"
		    "activeElement:x}),((jt=g.reactiveElementVersions)!=null?jt:g.reactiveElementVersions=[]).push(\"2.1.2\");"
		    "/**\n * @license\n * Copyright 2017 Google LLC\n * SPDX-License-Identifier: BSD-3-Clause\n */const O=glob"
		    "alThis,_t=s=>s,B=O.trustedTypes,yt=B?B.createPolicy(\"lit-html\",{createHTML:s=>s}):void 0,At=\"$lit$\",v"
		    "=`lit$${Math.random().toFixed(9).slice(2)}$`,wt=\"?\"+v,Yt=`<${wt}>`,y=document,H=()=>y.createComment(\""
		    "\"),N=s=>s===null||typeof s!=\"object\"&&typeof s!=\"function\",tt=Array.isArray,te=s=>tt(s)||typeof(s==n"
		    "ull?void 0:s[Symbol.iterator])==\"function\",et=`[ \t\n\\f\\r]`,R=/<(?:(!--|\\/[^a-zA-Z])|(\\/?[a-zA-Z][^"
		    ">\\s]*)|(\\/?$))/g,Et=/-->/g,kt=/>/g,A=RegExp(`>|${et}(?:([^\\\\s\"'>=/]+)(${et}*=${et}*(?:[^ \t\n\\f\\r"
		    "\"'\\`<>=]|(\"|')|))|$)`,\"g\"),xt=/'/g,St=/\"/g,Ct=/^(?:script|style|textarea|title)$/i,ee=s=>(t,...e)=>"
		    "({_$litType$:s,strings:t,values:e}),S=ee(1),m=Symbol.for(\"lit-noChange\"),b=Symbol.for(\"lit-nothing\"),"
		    "Pt=new WeakMap,w=y.createTreeWalker(y,129);function Tt(s,t){if(!tt(s)||!s.hasOwnProperty(\"raw\"))throw E"
		    "rror(\"invalid template strings array\");return yt!==void 0?yt.createHTML(t):t}const oe=(s,t)=>{const e=s"
		    ".length-1,o=[];let r,n=t===2?\"<svg>\":t===3?\"<math>\":\"\",i=R;for(let a=0;a<e;a++){const l=s[a];let h,"
		    "u,c=-1,p=0;for(;p<l.length&&(i.lastIndex=p,u=i.exec(l),u!==null);)p=i.lastIndex,i===R?u[1]===\"!--\"?i=Et"
		    ":u[1]!==void 0?i=kt:u[2]!==void 0?(Ct.test(u[2])&&(r=RegExp(\"</\"+u[2],\"g\")),i=A):u[3]!==void 0&&(i=A)"
		    ":i===A?u[0]===\">\"?(i=r!=null?r:R,c=-1):u[1]===void 0?c=-2:(c=i.lastIndex-u[2].length,h=u[1],i=u[3]===vo"
		    "id 0?A:u[3]==='\"'?St:xt):i===St||i===xt?i=A:i===Et||i===kt?i=R:(i=A,r=void 0);const d=i===A&&s[a+1].star"
		    "tsWith(\"/>\")?\" \":\"\";n+=i===R?l+Yt:c>=0?(o.push(h),l.slice(0,c)+At+l.slice(c)+v+d):l+v+(c===-2?a:d)}"
		    "return[Tt(s,n+(s[e]||\"<?>\")+(t===2?\"</svg>\":t===3?\"</math>\":\"\")),o]};class z{constructor({strings"
		    ":t,_$litType$:e},o){let r;this.parts=[];let n=0,i=0;const a=t.length-1,l=this.parts,[h,u]=oe(t,e);if(this"
		    ".el=z.createElement(h,o),w.currentNode=this.el.content,e===2||e===3){const c=this.el.content.firstChild;c"
		    ".replaceWith(...c.childNodes)}for(;(r=w.nextNode())!==null&&l.length<a;){if(r.nodeType===1){if(r.hasAttri"
		    "butes())for(const c of r.getAttributeNames())if(c.endsWith(At)){const p=u[i++],d=r.getAttribute(c).split("
		    "v),f=/([.?@])?(.*)/.exec(p);l.push({type:1,index:n,name:f[2],strings:d,ctor:f[1]===\".\"?re:f[1]===\"?\"?"
		    "ie:f[1]===\"@\"?ne:q}),r.removeAttribute(c)}else c.startsWith(v)&&(l.push({type:6,index:n}),r.removeAttri"
		    "bute(c));if(Ct.test(r.tagName)){const c=r.textContent.split(v),p=c.length-1;if(p>0){r.textContent=B?B.emp"
		    "tyScript:\"\";for(let d=0;d<p;d++)r.append(c[d],H()),w.nextNode(),l.push({type:2,index:++n});r.append(c[p"
		    "],H())}}}else if(r.nodeType===8)if(r.data===wt)l.push({type:2,index:n});else{let c=-1;for(;(c=r.data.inde"
		    "xOf(v,c+1))!==-1;)l.push({type:7,index:n}),c+=v.length-1}n++}}static createElement(t,e){const o=y.createE"
		    "lement(\"template\");return o.innerHTML=t,o}}function C(s,t,e=s,o){var i,a,l;if(t===m)return t;let r=o!=="
		    "void 0?(i=e._$Co)==null?void 0:i[o]:e._$Cl;const n=N(t)?void 0:t._$litDirective$;return(r==null?void 0:r."
		    "constructor)!==n&&((a=r==null?void 0:r._$AO)==null||a.call(r,!1),n===void 0?r=void 0:(r=new n(s),r._$AT(s"
		    ",e,o)),o!==void 0?((l=e._$Co)!=null?l:e._$Co=[])[o]=r:e._$Cl=r),r!==void 0&&(t=C(s,r._$AS(s,t.values),r,o"
		    ")),t}class se{constructor(t,e){this._$AV=[],this._$AN=void 0,this._$AD=t,this._$AM=e}get parentNode(){ret"
		    "urn this._$AM.parentNode}get _$AU(){return this._$AM._$AU}u(t){var h;const{el:{content:e},parts:o}=this._"
		    "$AD,r=((h=t==null?void 0:t.creationScope)!=null?h:y).importNode(e,!0);w.currentNode=r;let n=w.nextNode(),"
		    "i=0,a=0,l=o[0];for(;l!==void 0;){if(i===l.index){let u;l.type===2?u=new P(n,n.nextSibling,this,t):l.type="
		    "==1?u=new l.ctor(n,l.name,l.strings,this,t):l.type===6&&(u=new le(n,this,t)),this._$AV.push(u),l=o[++a]}i"
		    "!==(l==null?void 0:l.index)&&(n=w.nextNode(),i++)}return w.currentNode=y,r}p(t){let e=0;for(const o of th"
		    "is._$AV)o!==void 0&&(o.strings!==void 0?(o._$AI(t,o,e),e+=o.strings.length-2):o._$AI(t[e])),e++}}class P{"
		    "get _$AU(){var t,e;return(e=(t=this._$AM)==null?void 0:t._$AU)!=null?e:this._$Cv}constructor(t,e,o,r){var"
		    " n;this.type=2,this._$AH=b,this._$AN=void 0,this._$AA=t,this._$AB=e,this._$AM=o,this.options=r,this._$Cv="
		    "(n=r==null?void 0:r.isConnected)!=null?n:!0}get parentNode(){let t=this._$AA.parentNode;const e=this._$AM"
		    ";return e!==void 0&&(t==null?void 0:t.nodeType)===11&&(t=e.parentNode),t}get startNode(){return this._$AA"
		    "}get endNode(){return this._$AB}_$AI(t,e=this){t=C(this,t,e),N(t)?t===b||t==null||t===\"\"?(this._$AH!==b"
		    "&&this._$AR(),this._$AH=b):t!==this._$AH&&t!==m&&this._(t):t._$litType$!==void 0?this.$(t):t.nodeType!==v"
		    "oid 0?this.T(t):te(t)?this.k(t):this._(t)}O(t){return this._$AA.parentNode.insertBefore(t,this._$AB)}T(t)"
		    "{this._$AH!==t&&(this._$AR(),this._$AH=this.O(t))}_(t){this._$AH!==b&&N(this._$AH)?this._$AA.nextSibling."
		    "data=t:this.T(y.createTextNode(t)),this._$AH=t}$(t){var n;const{values:e,_$litType$:o}=t,r=typeof o==\"nu"
		    "mber\"?this._$AC(t):(o.el===void 0&&(o.el=z.createElement(Tt(o.h,o.h[0]),this.options)),o);if(((n=this._$"
		    "AH)==null?void 0:n._$AD)===r)this._$AH.p(e);else{const i=new se(r,this),a=i.u(this.options);i.p(e),this.T"
		    "(a),this._$AH=i}}_$AC(t){let e=Pt.get(t.strings);return e===void 0&&Pt.set(t.strings,e=new z(t)),e}k(t){t"
		    "t(this._$AH)||(this._$AH=[],this._$AR());const e=this._$AH;let o,r=0;for(const n of t)r===e.length?e.push"
		    "(o=new P(this.O(H()),this.O(H()),this,this.options)):o=e[r],o._$AI(n),r++;r<e.length&&(this._$AR(o&&o._$A"
		    "B.nextSibling,r),e.length=r)}_$AR(t=this._$AA.nextSibling,e){var o;for((o=this._$AP)==null?void 0:o.call("
		    "this,!1,!0,e);t!==this._$AB;){const r=_t(t).nextSibling;_t(t).remove(),t=r}}setConnected(t){var e;this._$"
		    "AM===void 0&&(this._$Cv=t,(e=this._$AP)==null||e.call(this,t))}}class q{get tagName(){return this.element"
		    ".tagName}get _$AU(){return this._$AM._$AU}constructor(t,e,o,r,n){this.type=1,this._$AH=b,this._$AN=void 0"
		    ",this.element=t,this.name=e,this._$AM=r,this.options=n,o.length>2||o[0]!==\"\"||o[1]!==\"\"?(this._$AH=Ar"
		    "ray(o.length-1).fill(new String),this.strings=o):this._$AH=b}_$AI(t,e=this,o,r){const n=this.strings;let "
		    "i=!1;if(n===void 0)t=C(this,t,e,0),i=!N(t)||t!==this._$AH&&t!==m,i&&(this._$AH=t);else{const a=t;let l,h;"
		    "for(t=n[0],l=0;l<n.length-1;l++)h=C(this,a[o+l],e,l),h===m&&(h=this._$AH[l]),i||(i=!N(h)||h!==this._$AH[l"
		    "]),h===b?t=b:t!==b&&(t+=(h!=null?h:\"\")+n[l+1]),this._$AH[l]=h}i&&!r&&this.j(t)}j(t){t===b?this.element."
		    "removeAttribute(this.name):this.element.setAttribute(this.name,t!=null?t:\"\")}}class re extends q{constr"
		    "uctor(){super(...arguments),this.type=3}j(t){this.element[this.name]=t===b?void 0:t}}class ie extends q{c"
		    "onstructor(){super(...arguments),this.type=4}j(t){this.element.toggleAttribute(this.name,!!t&&t!==b)}}cla"
		    "ss ne extends q{constructor(t,e,o,r,n){super(t,e,o,r,n),this.type=5}_$AI(t,e=this){var i;if((t=(i=C(this,"
		    "t,e,0))!=null?i:b)===m)return;const o=this._$AH,r=t===b&&o!==b||t.capture!==o.capture||t.once!==o.once||t"
		    ".passive!==o.passive,n=t!==b&&(o===b||r);r&&this.element.removeEventListener(this.name,this,o),n&&this.el"
		    "ement.addEventListener(this.name,this,t),this._$AH=t}handleEvent(t){var e,o;typeof this._$AH==\"function"
		    "\"?this._$AH.call((o=(e=this.options)==null?void 0:e.host)!=null?o:this.element,t):this._$AH.handleEvent("
		    "t)}}class le{constructor(t,e,o){this.element=t,this.type=6,this._$AN=void 0,this._$AM=e,this.options=o}ge"
		    "t _$AU(){return this._$AM._$AU}_$AI(t){C(this,t)}}const ae={I:P},ot=O.litHtmlPolyfillSupport;ot==null||ot"
		    "(z,P),((It=O.litHtmlVersions)!=null?It:O.litHtmlVersions=[]).push(\"3.3.2\");const ce=(s,t,e)=>{var n,i;c"
		    "onst o=(n=e==null?void 0:e.renderBefore)!=null?n:t;let r=o._$litPart$;if(r===void 0){const a=(i=e==null?v"
		    "oid 0:e.renderBefore)!=null?i:null;o._$litPart$=r=new P(t.insertBefore(H(),a),a,void 0,e!=null?e:{})}retu"
		    "rn r._$AI(s),r};/**\n * @license\n * Copyright 2017 Google LLC\n * SPDX-License-Identifier: BSD-3-Clause"
		    "\n */const E=globalThis;let _=class extends x{constructor(){super(...arguments),this.renderOptions={host:"
		    "this},this._$Do=void 0}createRenderRoot(){var e,o;const t=super.createRenderRoot();return(o=(e=this.rende"
		    "rOptions).renderBefore)!=null||(e.renderBefore=t.firstChild),t}update(t){const e=this.render();this.hasUp"
		    "dated||(this.renderOptions.isConnected=this.isConnected),super.update(t),this._$Do=ce(e,this.renderRoot,t"
		    "his.renderOptions)}connectedCallback(){var t;super.connectedCallback(),(t=this._$Do)==null||t.setConnecte"
		    "d(!0)}disconnectedCallback(){var t;super.disconnectedCallback(),(t=this._$Do)==null||t.setConnected(!1)}r"
		    "ender(){return m}};_._$litElement$=!0,_.finalized=!0,(Bt=E.litElementHydrateSupport)==null||Bt.call(E,{Li"
		    "tElement:_});const st=E.litElementPolyfillSupport;st==null||st({LitElement:_}),((qt=E.litElementVersions)"
		    "!=null?qt:E.litElementVersions=[]).push(\"4.2.2\");/**\n * @license\n * Copyright 2017 Google LLC\n * SPD"
		    "X-License-Identifier: BSD-3-Clause\n */const W=s=>(t,e)=>{e!==void 0?e.addInitializer(()=>{customElements"
		    ".define(s,t)}):customElements.define(s,t)};/**\n * @license\n * Copyright 2017 Google LLC\n * SPDX-Licens"
		    "e-Identifier: BSD-3-Clause\n */const he={attribute:!0,type:String,converter:I,reflect:!1,hasChanged:Y},ue"
		    "=(s=he,t,e)=>{const{kind:o,metadata:r}=e;let n=globalThis.litPropertyMetadata.get(r);if(n===void 0&&globa"
		    "lThis.litPropertyMetadata.set(r,n=new Map),o===\"setter\"&&((s=Object.create(s)).wrapped=!0),n.set(e.name"
		    ",s),o===\"accessor\"){const{name:i}=e;return{set(a){const l=t.get.call(this);t.set.call(this,a),this.requ"
		    "estUpdate(i,l,s,!0,a)},init(a){return a!==void 0&&this.C(i,void 0,s,a),a}}}if(o===\"setter\"){const{name:"
		    "i}=e;return function(a){const l=this[i];t.call(this,a),this.requestUpdate(i,l,s,!0,a)}}throw Error(\"Unsu"
		    "pported decorator location: \"+o)};function de(s){return(t,e)=>typeof e==\"object\"?ue(s,t,e):((o,r,n)=>{"
		    "const i=r.hasOwnProperty(n);return r.constructor.createProperty(n,o),i?Object.getOwnPropertyDescriptor(r,"
		    "n):void 0})(s,t,e)}class pe extends Event{constructor(t){super(\"subtitlechanged\"),this.subtitle=t}}cons"
		    "t V=window;function be(s,t){const e=()=>{var o;if(Date.now()-t.then>1e4){clearTimeout(t.timer),console.lo"
		    "g(\"-> <fallback>\"),s(\"\");return}const r=(o=V.get_version)==null?void 0:o.call(V);r!==void 0&&(clearTi"
		    "meout(t.timer),r.then(n=>{n===void 0?(console.log(\"no value....\"),t.timer=setInterval(e,100)):(console."
		    "log(\"->\",n),s(n))}))};return e}let rt=\"\";function fe(s){s!==rt&&(rt=s,window.dispatchEvent(new pe(s))"
		    ")}function $e(){return rt}async function ge(){return console.log(\">>> get_version()\"),new Promise(s=>{c"
		    "onst t={timer:-1,then:Date.now()},e=be(s,t);t.timer=setInterval(e,100)})}var it,Ut,Q;class ve{constructor"
		    "(t){it.add(this),this.version=\"\",this.subtitle=$e(),Q.set(this,e=>{this.setSubtitle(e.subtitle)}),this."
		    "host=t,t.addController(this),U(this,it,\"m\",Ut).call(this)}get title(){return this.subtitle?`${this.subt"
		    "itle} - Quick-DRA ${this.version}`:`Quick-DRA ${this.version}`}hostConnected(){window.addEventListener(\""
		    "subtitlechanged\",U(this,Q,\"f\"))}hostDisconnected(){window.removeEventListener(\"subtitlechanged\",U(th"
		    "is,Q,\"f\"))}updateTitle(){this.host.requestUpdate(),document.getElementsByTagName(\"title\")[0].innerTex"
		    "t=this.title}setVersion(t){this.version=t,this.updateTitle()}setSubtitle(t){this.subtitle=t,this.updateTi"
		    "tle()}}Q=new WeakMap,it=new WeakSet,Ut=async function(){this.setVersion(await ge())};const me=j`:host{hei"
		    "ght:36px;background:rgba(0,0,0,.25);-webkit-app-region:drag;--webui-app-region:drag;display:flex;align-it"
		    "ems:center;justify-content:space-between;padding:0;padding-left:6px;flex-shrink:0}.banner{height:100%;dis"
		    "play:inline-flex;align-items:center;justify-content:space-between;gap:.5em}`;/**\n * @license\n * Copyrig"
		    "ht 2017 Google LLC\n * SPDX-License-Identifier: BSD-3-Clause\n */const Mt={CHILD:2},Ot=s=>(...t)=>({_$lit"
		    "Directive$:s,values:t});let Ht=class{constructor(t){}get _$AU(){return this._$AM._$AU}_$AT(t,e,o){this._$"
		    "Ct=t,this._$AM=e,this._$Ci=o}_$AS(t,e){return this.update(t,e)}update(t,e){return this.render(...e)}};/**"
		    "\n * @license\n * Copyright 2017 Google LLC\n * SPDX-License-Identifier: BSD-3-Clause\n */let nt=class ex"
		    "tends Ht{constructor(t){if(super(t),this.it=b,t.type!==Mt.CHILD)throw Error(this.constructor.directiveNam"
		    "e+\"() can only be used in child bindings\")}render(t){if(t===b||t==null)return this._t=void 0,this.it=t;"
		    "if(t===m)return t;if(typeof t!=\"string\")throw Error(this.constructor.directiveName+\"() called with a n"
		    "on-string value\");if(t===this.it)return this._t;this.it=t;const e=[t];return e.raw=e,this._t={_$litType$"
		    ":this.constructor.resultType,strings:e,values:[]}}};nt.directiveName=\"unsafeHTML\",nt.resultType=1;/**\n"
		    " * @license\n * Copyright 2017 Google LLC\n * SPDX-License-Identifier: BSD-3-Clause\n */let lt=class exte"
		    "nds nt{};lt.directiveName=\"unsafeSVG\",lt.resultType=2;const _e=Ot(lt);class ye{constructor(t){this.svg="
		    "\"\",this.host=t,this.host.addController(this)}async hostConnected(){const t=await fetch(\"/favicon.svg\""
		    ");this.svg=await t.text(),this.host.requestUpdate()}}let at=class extends _{constructor(){super(...argume"
		    "nts),this.controller=new ye(this)}render(){const{svg:t}=this.controller;return _e(t)}};at.styles=j`\n    "
		    ":host {\n      height: 24px;\n      width: 24px;\n      display: inline-block;\n\n      svg {\n        wi"
		    "dth: 100%;\n        height: 100%;\n        fill: var(--logo-fill);\n      }\n    }\n  `,at=T([W(\"fav-ico"
		    "n\")],at);const Ae=j`\n  :host {\n    display: flex;\n    height: 100%;\n    align-items: stretch;\n  }\n"
		    "\n  .container {\n    display: flex;\n    align-items: center;\n    &.web {\n      gap: 0.5em;\n      mar"
		    "gin-right: 1em;\n    }\n  }\n\n  button {\n    border: none;\n    margin: 0;\n    padding: 0;\n    width:"
		    " auto;\n    overflow: visible;\n\n    background: transparent;\n\n    /* inherit font & color from ancest"
		    "or */\n    color: inherit;\n    font: inherit;\n\n    line-height: normal;\n\n    /* Corrects font smooth"
		    "ing for webkit */\n    -webkit-font-smoothing: inherit;\n    -moz-osx-font-smoothing: inherit;\n\n    -we"
		    "bkit-appearance: none;\n\n    --transition: var(--sys-button-transition, 0.5s);\n\n    --text-color-norma"
		    "l: var(--sys-button-text-color, #000000);\n    --background-color-normal: var(--sys-button-background-col"
		    "or, transparent);\n\n    --text-color-hover: var(--sys-button-text-color-hover, #ebebeb);\n    --backgrou"
		    "nd-color-hover: var(\n      --sys-button-background-color-hover,\n      rgb(0 0 0 / 0.6)\n    );\n\n    -"
		    "-text-color-close: var(--sys-button-text-color-close, var(--text-color));\n    --background-color-close: "
		    "var(\n      --sys-button-background-color-close,\n      var(--sys-button-background-color)\n    );\n\n   "
		    " --text-color-hover-close: var(\n      --sys-button-text-color-hover-close,\n      var(--sys-button-text-"
		    "color-hover)\n    );\n    --background-color-hover-close: var(\n      --sys-button-background-color-hover"
		    "-close,\n      rgb(from var(--background-color-hover) 128 0 0 / A)\n    );\n  }\n\n  .button {\n    displ"
		    "ay: inline-block;\n    line-height: 1;\n    font-size: 0.7em;\n    width: 4em;\n    height: 100%;\n    cu"
		    "rsor: pointer;\n    color: var(--text-color);\n    background-color: var(--background-color);\n    transi"
		    "tion: all var(--transition) ease-out;\n\n    --text-color: var(--text-color-normal);\n    --background-co"
		    "lor: var(--background-color-normal);\n\n    &:hover {\n      --text-color: var(--text-color-hover);\n    "
		    "  --background-color: var(--background-color-hover);\n    }\n  }\n\n  .win .button {\n    font-family: 'S"
		    "egoe MDL2 Assets';\n\n    &.close {\n      --text-color-normal: var(--text-color-close);\n      --backgro"
		    "und-color-normal: var(--background-color-close);\n      --text-color-hover: var(--text-color-hover-close)"
		    ";\n      --background-color-hover: var(--background-color-hover-close);\n    }\n  }\n\n  .web .button {\n"
		    "    border-radius: 50%;\n    padding: auto;\n    width: 20px;\n    height: 20px;\n\n    span {\n      vis"
		    "ibility: hidden;\n    }\n\n    &:hover {\n      transform: scale(1.1);\n    }\n\n    &.minimize {\n      "
		    "--background-color-normal: var(\n        --web-button-background-color-minimize,\n        yellow\n      )"
		    ";\n      --background-color-hover: var(\n        --web-button-background-color-hover-minimize,\n        o"
		    "klab(from var(--background-color) calc(L * 0.9) a b)\n      );\n    }\n\n    &.close {\n      --backgroun"
		    "d-color-normal: var(\n        --web-button-background-color-close,\n        yellow\n      );\n      --bac"
		    "kground-color-hover: var(\n        --web-button-background-color-hover-close,\n        oklab(from var(--b"
		    "ackground-color) calc(L * 0.9) a b)\n      );\n    }\n  }\n`;/**\n * @license\n * Copyright 2020 Google L"
		    "LC\n * SPDX-License-Identifier: BSD-3-Clause\n */const{I:we}=ae,Nt=s=>s,Rt=()=>document.createComment(\""
		    "\"),L=(s,t,e)=>{var n;const o=s._$AA.parentNode,r=t===void 0?s._$AB:t._$AA;if(e===void 0){const i=o.inser"
		    "tBefore(Rt(),r),a=o.insertBefore(Rt(),r);e=new we(i,a,s,s.options)}else{const i=e._$AB.nextSibling,a=e._$"
		    "AM,l=a!==s;if(l){let h;(n=e._$AQ)==null||n.call(e,s),e._$AM=s,e._$AP!==void 0&&(h=s._$AU)!==a._$AU&&e._$A"
		    "P(h)}if(i!==r||l){let h=e._$AA;for(;h!==i;){const u=Nt(h).nextSibling;Nt(o).insertBefore(h,r),h=u}}}retur"
		    "n e},k=(s,t,e=s)=>(s._$AI(t,e),s),Ee={},ke=(s,t=Ee)=>s._$AH=t,xe=s=>s._$AH,ct=s=>{s._$AR(),s._$AA.remove("
		    ")};/**\n * @license\n * Copyright 2017 Google LLC\n * SPDX-License-Identifier: BSD-3-Clause\n */const Lt="
		    "(s,t,e)=>{const o=new Map;for(let r=t;r<=e;r++)o.set(s[r],r);return o},Se=Ot(class extends Ht{constructor"
		    "(s){if(super(s),s.type!==Mt.CHILD)throw Error(\"repeat() can only be used in text expressions\")}dt(s,t,e"
		    "){let o;e===void 0?e=t:t!==void 0&&(o=t);const r=[],n=[];let i=0;for(const a of s)r[i]=o?o(a,i):i,n[i]=e("
		    "a,i),i++;return{values:n,keys:r}}render(s,t,e){return this.dt(s,t,e).values}update(s,[t,e,o]){var pt;cons"
		    "t r=xe(s),{values:n,keys:i}=this.dt(t,e,o);if(!Array.isArray(r))return this.ut=i,n;const a=(pt=this.ut)!="
		    "null?pt:this.ut=[],l=[];let h,u,c=0,p=r.length-1,d=0,f=n.length-1;for(;c<=p&&d<=f;)if(r[c]===null)c++;els"
		    "e if(r[p]===null)p--;else if(a[c]===i[d])l[d]=k(r[c],n[d]),c++,d++;else if(a[p]===i[f])l[f]=k(r[p],n[f]),"
		    "p--,f--;else if(a[c]===i[f])l[f]=k(r[c],n[f]),L(s,l[f+1],r[c]),c++,f--;else if(a[p]===i[d])l[d]=k(r[p],n["
		    "d]),L(s,r[c],r[p]),p--,d++;else if(h===void 0&&(h=Lt(i,d,f),u=Lt(a,c,p)),h.has(a[c]))if(h.has(a[p])){cons"
		    "t $=u.get(i[d]),G=$!==void 0?r[$]:null;if(G===null){const bt=L(s,r[c]);k(bt,n[d]),l[d]=bt}else l[d]=k(G,n"
		    "[d]),L(s,r[c],G),r[$]=null;d++}else ct(r[p]),p--;else ct(r[c]),c++;for(;d<=f;){const $=L(s,l[f+1]);k($,n["
		    "d]),l[d++]=$}for(;c<=p;){const $=r[c++];$!==null&&ct($)}return this.ut=i,ke(s,l),m}}),Ce=[{class_name:\"m"
		    "inimize\",win_icon:\"\\uE921\",onclick:()=>{var s,t;return(t=(s=V).minimize)==null?void 0:t.call(s)}},{cl"
		    "ass_name:\"close\",win_icon:\"\\uE8BB\",onclick:()=>{var s,t;return(t=(s=V).close_win)==null?void 0:t.cal"
		    "l(s)}}];let Z=class extends _{constructor(){super(...arguments),this.platform=\"web\"}render(){return S` "
		    "<span class=\"container ${this.platform}\"> ${Se(Ce,({class_name:t,win_icon:e,onclick:o})=>S`<button clas"
		    "s=\"button ${t}\" @click=\"${o}\"> <span>${e}</span> </button>`)} </span> `}};Z.styles=Ae,T([de({type:Str"
		    "ing})],Z.prototype,\"platform\",void 0),Z=T([W(\"title-buttons\")],Z);var F,ht;let ut=class extends _{con"
		    "structor(){super(...arguments),F.add(this),this.controller=new ve(this)}render(){const s=navigator.platfo"
		    "rm==\"Win32\"?\"win\":\"web\",t=s===\"win\"?S`<span class=\"banner\">${U(this,F,\"m\",ht).call(this)}</sp"
		    "an>`:U(this,F,\"m\",ht).call(this);return S` ${t} <title-buttons platform=\"${s}\"></title-buttons> `}};F"
		    "=new WeakSet,ht=function(){return S` <fav-icon></fav-icon> <span>${this.controller.title}</span> `},ut.st"
		    "yles=me,ut=T([W(\"title-bar\")],ut);let dt=class extends _{render(){return S` <title-bar></title-bar> <ma"
		    "in> <button @click=\"${()=>fe(\"Settings\")}\">set title</button> </main> `}};dt.styles=j`\n    :host {\n"
		    "      background-color: rgb(from var(--system-background-color) r g b / 0.95);\n      color: var(--system"
		    "-on-background-color);\n      width: 100%;\n      height: 100%;\n      overflow: hidden;\n      display: "
		    "flex;\n      flex-direction: column;\n      border-radius: 7px;\n      backdrop-filter: blur(24px);\n    "
		    "  -webkit-backdrop-filter: blur(24px);\n\n      --primary-color: rgb(73 103 45);\n      --system-backgrou"
		    "nd-color: rgb(245 246 228);\n      --system-on-background-color: rgb(26 29 22);\n      --logo-fill: #0092"
		    "3f;\n\n      --sys-button-text-color: #000000;\n      --sys-button-text-color-hover: #ebebeb;\n      --sy"
		    "s-button-background-color: transparent;\n      --sys-button-background-color-hover: rgb(0 0 0 / 0.5);\n\n"
		    "      --sys-button-text-color-close: var(--sys-button-text-color);\n      --sys-button-text-color-hover-c"
		    "lose: var(--sys-button-text-color-hover);\n      --sys-button-background-color-close: var(--sys-button-ba"
		    "ckground-color);\n      --sys-button-background-color-hover-close: rgb(\n        from var(--sys-button-ba"
		    "ckground-color-hover) 192 0 0 / alpha\n      );\n\n      --web-button-background-color-minimize: #ffbd2e;"
		    "\n      --web-button-background-color-hover-minimize: oklab(\n        from var(--web-button-background-co"
		    "lor-minimize) calc(L * 0.9) a b\n      );\n\n      --web-button-background-color-close: #ff5f57;\n      -"
		    "-web-button-background-color-hover-close: oklab(\n        from var(--web-button-background-color-close) c"
		    "alc(L * 0.9) a b\n      );\n\n      --sys-button-transition: 0.3s;\n\n      @media (prefers-color-scheme:"
		    " dark) {\n        --primary-color: rgb(175 209 140);\n        --system-background-color: rgb(26 29 22);\n"
		    "        --system-on-background-color: rgb(226 227 217);\n        --logo-fill: oklab(from #00923f calc((L "
		    "+ 1) / 2) a b);\n\n        --sys-button-text-color: var(--sys-button-text-color-hover);\n        --sys-bu"
		    "tton-background-color-hover-close: rgb(\n          from var(--sys-button-background-color-hover) 128 0 0 "
		    "/ alpha\n        );\n\n        --web-button-background-color-minimize: #ffbd2e;\n        --web-button-bac"
		    "kground-color-hover-minimize: oklab(\n          from var(--web-button-background-color-minimize) calc(L *"
		    " 1.15) a b\n        );\n\n        --web-button-background-color-close: #ff5f57;\n        --web-button-bac"
		    "kground-color-hover-close: oklab(\n          from var(--web-button-background-color-close) calc(L * 1.15)"
		    " a b\n        );\n      }\n    }\n  `,dt=T([W(\"qdra-app\")],dt),window.addEventListener(\"load\",()=>{co"
		    "nst s=document.createElement(\"qdra-app\");document.getElementsByTagName(\"body\")[0].appendChild(s)});\n"
		    ""sv;

		static constexpr auto file_sw_js =
		    "if(!self.define){let e,i={};const n=(n,t)=>(n=new URL(n+\".js\",t).href,i[n]||new Promise(i=>{if(\"docume"
		    "nt\"in self){const e=document.createElement(\"script\");e.src=n,e.onload=i,document.head.appendChild(e)}e"
		    "lse e=n,importScripts(n),i()}).then(()=>{let e=i[n];if(!e)throw new Error(`Module ${n} didn\xE2\x80\x99"
		    "t register its module`);return e}));self.define=(t,o)=>{const r=e||(\"document\"in self?document.currentS"
		    "cript.src:\"\")||location.href;if(i[r])return;let s={};const l=e=>n(e,r),c={module:{uri:r},exports:s,requ"
		    "ire:l};i[r]=Promise.all(t.map(e=>c[e]||l(e))).then(e=>(o(...e),s))}}define([\"./workbox-19e8203f\"],funct"
		    "ion(e){\"use strict\";self.skipWaiting(),e.clientsClaim(),e.precacheAndRoute([{url:\"index.js\",revision:"
		    "\"47db655b5e5e21c27d940004c4d6ec34\"},{url:\"index.html\",revision:\"afc1670ee5e0b97ab54b871d7cb26372\"}]"
		    ",{}),e.registerRoute(new e.NavigationRoute(e.createHandlerBoundToURL(\"/index.html\"))),e.registerRoute("
		    "\"polyfills/*.js\",new e.CacheFirst,\"GET\")});\n"
		    ""sv;

		static constexpr auto file_workbox_19e8203f_js =
		    "define([\"exports\"],function(t){\"use strict\";try{self[\"workbox:core:7.3.0\"]&&_()}catch(t){}const e=("
		    "t,...e)=>{let s=t;return e.length>0&&(s+=` :: ${JSON.stringify(e)}`),s};class s extends Error{constructor"
		    "(t,s){super(e(t,s)),this.name=t,this.details=s}}try{self[\"workbox:routing:7.3.0\"]&&_()}catch(t){}const "
		    "n=t=>t&&\"object\"==typeof t?t:{handle:t};class r{constructor(t,e,s=\"GET\"){this.handler=n(e),this.match"
		    "=t,this.method=s}setCatchHandler(t){this.catchHandler=n(t)}}class i extends r{constructor(t,e,s){super(({"
		    "url:e})=>{const s=t.exec(e.href);if(s&&(e.origin===location.origin||0===s.index))return s.slice(1)},e,s)}"
		    "}class o{constructor(){this.t=new Map,this.i=new Map}get routes(){return this.t}addFetchListener(){self.a"
		    "ddEventListener(\"fetch\",t=>{const{request:e}=t,s=this.handleRequest({request:e,event:t});s&&t.respondWi"
		    "th(s)})}addCacheListener(){self.addEventListener(\"message\",t=>{if(t.data&&\"CACHE_URLS\"===t.data.type)"
		    "{const{payload:e}=t.data,s=Promise.all(e.urlsToCache.map(e=>{\"string\"==typeof e&&(e=[e]);const s=new Re"
		    "quest(...e);return this.handleRequest({request:s,event:t})}));t.waitUntil(s),t.ports&&t.ports[0]&&s.then("
		    "()=>t.ports[0].postMessage(!0))}})}handleRequest({request:t,event:e}){const s=new URL(t.url,location.href"
		    ");if(!s.protocol.startsWith(\"http\"))return;const n=s.origin===location.origin,{params:r,route:i}=this.f"
		    "indMatchingRoute({event:e,request:t,sameOrigin:n,url:s});let o=i&&i.handler;const c=t.method;if(!o&&this."
		    "i.has(c)&&(o=this.i.get(c)),!o)return;let a;try{a=o.handle({url:s,request:t,event:e,params:r})}catch(t){a"
		    "=Promise.reject(t)}const h=i&&i.catchHandler;return a instanceof Promise&&(this.o||h)&&(a=a.catch(async n"
		    "=>{if(h)try{return await h.handle({url:s,request:t,event:e,params:r})}catch(t){t instanceof Error&&(n=t)}"
		    "if(this.o)return this.o.handle({url:s,request:t,event:e});throw n})),a}findMatchingRoute({url:t,sameOrigi"
		    "n:e,request:s,event:n}){const r=this.t.get(s.method)||[];for(const i of r){let r;const o=i.match({url:t,s"
		    "ameOrigin:e,request:s,event:n});if(o)return r=o,(Array.isArray(r)&&0===r.length||o.constructor===Object&&"
		    "0===Object.keys(o).length||\"boolean\"==typeof o)&&(r=void 0),{route:i,params:r}}return{}}setDefaultHandl"
		    "er(t,e=\"GET\"){this.i.set(e,n(t))}setCatchHandler(t){this.o=n(t)}registerRoute(t){this.t.has(t.method)||"
		    "this.t.set(t.method,[]),this.t.get(t.method).push(t)}unregisterRoute(t){if(!this.t.has(t.method))throw ne"
		    "w s(\"unregister-route-but-not-found-with-method\",{method:t.method});const e=this.t.get(t.method).indexO"
		    "f(t);if(!(e>-1))throw new s(\"unregister-route-route-not-registered\");this.t.get(t.method).splice(e,1)}}"
		    "let c;const a=()=>(c||(c=new o,c.addFetchListener(),c.addCacheListener()),c);function h(t,e,n){let o;if("
		    "\"string\"==typeof t){const s=new URL(t,location.href);o=new r(({url:t})=>t.href===s.href,e,n)}else if(t "
		    "instanceof RegExp)o=new i(t,e,n);else if(\"function\"==typeof t)o=new r(t,e,n);else{if(!(t instanceof r))"
		    "throw new s(\"unsupported-route-type\",{moduleName:\"workbox-routing\",funcName:\"registerRoute\",paramNa"
		    "me:\"capture\"});o=t}return a().registerRoute(o),o}const u={googleAnalytics:\"googleAnalytics\",precache:"
		    "\"precache-v2\",prefix:\"workbox\",runtime:\"runtime\",suffix:\"undefined\"!=typeof registration?registra"
		    "tion.scope:\"\"},l=t=>[u.prefix,t,u.suffix].filter(t=>t&&t.length>0).join(\"-\"),f=t=>t||l(u.precache),w="
		    "t=>t||l(u.runtime);function d(t,e){const s=new URL(t);for(const t of e)s.searchParams.delete(t);return s."
		    "href}class p{constructor(){this.promise=new Promise((t,e)=>{this.resolve=t,this.reject=e})}}const y=new S"
		    "et;try{self[\"workbox:strategies:7.3.0\"]&&_()}catch(t){}function g(t){return\"string\"==typeof t?new Req"
		    "uest(t):t}class R{constructor(t,e){this.h={},Object.assign(this,e),this.event=e.event,this.u=t,this.l=new"
		    " p,this.p=[],this.R=[...t.plugins],this.m=new Map;for(const t of this.R)this.m.set(t,{});this.event.waitU"
		    "ntil(this.l.promise)}async fetch(t){const{event:e}=this;let n=g(t);if(\"navigate\"===n.mode&&e instanceof"
		    " FetchEvent&&e.preloadResponse){const t=await e.preloadResponse;if(t)return t}const r=this.hasCallback(\""
		    "fetchDidFail\")?n.clone():null;try{for(const t of this.iterateCallbacks(\"requestWillFetch\"))n=await t({"
		    "request:n.clone(),event:e})}catch(t){if(t instanceof Error)throw new s(\"plugin-error-request-will-fetch"
		    "\",{thrownErrorMessage:t.message})}const i=n.clone();try{let t;t=await fetch(n,\"navigate\"===n.mode?void"
		    " 0:this.u.fetchOptions);for(const s of this.iterateCallbacks(\"fetchDidSucceed\"))t=await s({event:e,requ"
		    "est:i,response:t});return t}catch(t){throw r&&await this.runCallbacks(\"fetchDidFail\",{error:t,event:e,o"
		    "riginalRequest:r.clone(),request:i.clone()}),t}}async fetchAndCachePut(t){const e=await this.fetch(t),s=e"
		    ".clone();return this.waitUntil(this.cachePut(t,s)),e}async cacheMatch(t){const e=g(t);let s;const{cacheNa"
		    "me:n,matchOptions:r}=this.u,i=await this.getCacheKey(e,\"read\"),o=Object.assign(Object.assign({},r),{cac"
		    "heName:n});s=await caches.match(i,o);for(const t of this.iterateCallbacks(\"cachedResponseWillBeUsed\"))s"
		    "=await t({cacheName:n,matchOptions:r,cachedResponse:s,request:i,event:this.event})||void 0;return s}async"
		    " cachePut(t,e){const n=g(t);var r;await(r=0,new Promise(t=>setTimeout(t,r)));const i=await this.getCacheK"
		    "ey(n,\"write\");if(!e)throw new s(\"cache-put-with-no-response\",{url:(o=i.url,new URL(String(o),location"
		    ".href).href.replace(new RegExp(`^${location.origin}`),\"\"))});var o;const c=await this.v(e);if(!c)return"
		    "!1;const{cacheName:a,matchOptions:h}=this.u,u=await self.caches.open(a),l=this.hasCallback(\"cacheDidUpda"
		    "te\"),f=l?await async function(t,e,s,n){const r=d(e.url,s);if(e.url===r)return t.match(e,n);const i=Objec"
		    "t.assign(Object.assign({},n),{ignoreSearch:!0}),o=await t.keys(e,i);for(const e of o)if(r===d(e.url,s))re"
		    "turn t.match(e,n)}(u,i.clone(),[\"__WB_REVISION__\"],h):null;try{await u.put(i,l?c.clone():c)}catch(t){if"
		    "(t instanceof Error)throw\"QuotaExceededError\"===t.name&&await async function(){for(const t of y)await t"
		    "()}(),t}for(const t of this.iterateCallbacks(\"cacheDidUpdate\"))await t({cacheName:a,oldResponse:f,newRe"
		    "sponse:c.clone(),request:i,event:this.event});return!0}async getCacheKey(t,e){const s=`${t.url} | ${e}`;i"
		    "f(!this.h[s]){let n=t;for(const t of this.iterateCallbacks(\"cacheKeyWillBeUsed\"))n=g(await t({mode:e,re"
		    "quest:n,event:this.event,params:this.params}));this.h[s]=n}return this.h[s]}hasCallback(t){for(const e of"
		    " this.u.plugins)if(t in e)return!0;return!1}async runCallbacks(t,e){for(const s of this.iterateCallbacks("
		    "t))await s(e)}*iterateCallbacks(t){for(const e of this.u.plugins)if(\"function\"==typeof e[t]){const s=th"
		    "is.m.get(e),n=n=>{const r=Object.assign(Object.assign({},n),{state:s});return e[t](r)};yield n}}waitUntil"
		    "(t){return this.p.push(t),t}async doneWaiting(){for(;this.p.length;){const t=this.p.splice(0),e=(await Pr"
		    "omise.allSettled(t)).find(t=>\"rejected\"===t.status);if(e)throw e.reason}}destroy(){this.l.resolve(null)"
		    "}async v(t){let e=t,s=!1;for(const t of this.iterateCallbacks(\"cacheWillUpdate\"))if(e=await t({request:"
		    "this.request,response:e,event:this.event})||void 0,s=!0,!e)break;return s||e&&200!==e.status&&(e=void 0),"
		    "e}}class m{constructor(t={}){this.cacheName=w(t.cacheName),this.plugins=t.plugins||[],this.fetchOptions=t"
		    ".fetchOptions,this.matchOptions=t.matchOptions}handle(t){const[e]=this.handleAll(t);return e}handleAll(t)"
		    "{t instanceof FetchEvent&&(t={event:t,request:t.request});const e=t.event,s=\"string\"==typeof t.request?"
		    "new Request(t.request):t.request,n=\"params\"in t?t.params:void 0,r=new R(this,{event:e,request:s,params:"
		    "n}),i=this.q(r,s,e);return[i,this.U(i,r,s,e)]}async q(t,e,n){let r;await t.runCallbacks(\"handlerWillStar"
		    "t\",{event:n,request:e});try{if(r=await this.L(e,t),!r||\"error\"===r.type)throw new s(\"no-response\",{u"
		    "rl:e.url})}catch(s){if(s instanceof Error)for(const i of t.iterateCallbacks(\"handlerDidError\"))if(r=awa"
		    "it i({error:s,event:n,request:e}),r)break;if(!r)throw s}for(const s of t.iterateCallbacks(\"handlerWillRe"
		    "spond\"))r=await s({event:n,request:e,response:r});return r}async U(t,e,s,n){let r,i;try{r=await t}catch("
		    "i){}try{await e.runCallbacks(\"handlerDidRespond\",{event:n,request:s,response:r}),await e.doneWaiting()}"
		    "catch(t){t instanceof Error&&(i=t)}if(await e.runCallbacks(\"handlerDidComplete\",{event:n,request:s,resp"
		    "onse:r,error:i}),e.destroy(),i)throw i}}function v(t,e){const s=e();return t.waitUntil(s),s}try{self[\"wo"
		    "rkbox:precaching:7.3.0\"]&&_()}catch(t){}function q(t){if(!t)throw new s(\"add-to-cache-list-unexpected-t"
		    "ype\",{entry:t});if(\"string\"==typeof t){const e=new URL(t,location.href);return{cacheKey:e.href,url:e.h"
		    "ref}}const{revision:e,url:n}=t;if(!n)throw new s(\"add-to-cache-list-unexpected-type\",{entry:t});if(!e){"
		    "const t=new URL(n,location.href);return{cacheKey:t.href,url:t.href}}const r=new URL(n,location.href),i=ne"
		    "w URL(n,location.href);return r.searchParams.set(\"__WB_REVISION__\",e),{cacheKey:r.href,url:i.href}}clas"
		    "s U{constructor(){this.updatedURLs=[],this.notUpdatedURLs=[],this.handlerWillStart=async({request:t,state"
		    ":e})=>{e&&(e.originalRequest=t)},this.cachedResponseWillBeUsed=async({event:t,state:e,cachedResponse:s})="
		    ">{if(\"install\"===t.type&&e&&e.originalRequest&&e.originalRequest instanceof Request){const t=e.original"
		    "Request.url;s?this.notUpdatedURLs.push(t):this.updatedURLs.push(t)}return s}}}class L{constructor({precac"
		    "heController:t}){this.cacheKeyWillBeUsed=async({request:t,params:e})=>{const s=(null==e?void 0:e.cacheKey"
		    ")||this._.getCacheKeyForURL(t.url);return s?new Request(s,{headers:t.headers}):t},this._=t}}let b,E;async"
		    " function C(t,e){let n=null;if(t.url){n=new URL(t.url).origin}if(n!==self.location.origin)throw new s(\"c"
		    "ross-origin-copy-response\",{origin:n});const r=t.clone(),i={headers:new Headers(r.headers),status:r.stat"
		    "us,statusText:r.statusText},o=e?e(i):i,c=function(){if(void 0===b){const t=new Response(\"\");if(\"body\""
		    "in t)try{new Response(t.body),b=!0}catch(t){b=!1}b=!1}return b}()?r.body:await r.blob();return new Respon"
		    "se(c,o)}class x extends m{constructor(t={}){t.cacheName=f(t.cacheName),super(t),this.C=!1!==t.fallbackToN"
		    "etwork,this.plugins.push(x.copyRedirectedCacheableResponsesPlugin)}async L(t,e){const s=await e.cacheMatc"
		    "h(t);return s||(e.event&&\"install\"===e.event.type?await this.O(t,e):await this.N(t,e))}async N(t,e){let"
		    " n;const r=e.params||{};if(!this.C)throw new s(\"missing-precache-entry\",{cacheName:this.cacheName,url:t"
		    ".url});{const s=r.integrity,i=t.integrity,o=!i||i===s;n=await e.fetch(new Request(t,{integrity:\"no-cors"
		    "\"!==t.mode?i||s:void 0})),s&&o&&\"no-cors\"!==t.mode&&(this.j(),await e.cachePut(t,n.clone()))}return n}"
		    "async O(t,e){this.j();const n=await e.fetch(t);if(!await e.cachePut(t,n.clone()))throw new s(\"bad-precac"
		    "hing-response\",{url:t.url,status:n.status});return n}j(){let t=null,e=0;for(const[s,n]of this.plugins.en"
		    "tries())n!==x.copyRedirectedCacheableResponsesPlugin&&(n===x.defaultPrecacheCacheabilityPlugin&&(t=s),n.c"
		    "acheWillUpdate&&e++);0===e?this.plugins.push(x.defaultPrecacheCacheabilityPlugin):e>1&&null!==t&&this.plu"
		    "gins.splice(t,1)}}x.defaultPrecacheCacheabilityPlugin={cacheWillUpdate:async({response:t})=>!t||t.status>"
		    "=400?null:t},x.copyRedirectedCacheableResponsesPlugin={cacheWillUpdate:async({response:t})=>t.redirected?"
		    "await C(t):t};class O{constructor({cacheName:t,plugins:e=[],fallbackToNetwork:s=!0}={}){this.k=new Map,th"
		    "is.K=new Map,this.P=new Map,this.u=new x({cacheName:f(t),plugins:[...e,new L({precacheController:this})],"
		    "fallbackToNetwork:s}),this.install=this.install.bind(this),this.activate=this.activate.bind(this)}get str"
		    "ategy(){return this.u}precache(t){this.addToCacheList(t),this.T||(self.addEventListener(\"install\",this."
		    "install),self.addEventListener(\"activate\",this.activate),this.T=!0)}addToCacheList(t){const e=[];for(co"
		    "nst n of t){\"string\"==typeof n?e.push(n):n&&void 0===n.revision&&e.push(n.url);const{cacheKey:t,url:r}="
		    "q(n),i=\"string\"!=typeof n&&n.revision?\"reload\":\"default\";if(this.k.has(r)&&this.k.get(r)!==t)throw "
		    "new s(\"add-to-cache-list-conflicting-entries\",{firstEntry:this.k.get(r),secondEntry:t});if(\"string\"!="
		    "typeof n&&n.integrity){if(this.P.has(t)&&this.P.get(t)!==n.integrity)throw new s(\"add-to-cache-list-conf"
		    "licting-integrities\",{url:r});this.P.set(t,n.integrity)}if(this.k.set(r,t),this.K.set(r,i),e.length>0){c"
		    "onst t=`Workbox is precaching URLs without revision info: ${e.join(\", \")}\\nThis is generally NOT safe."
		    " Learn more at https://bit.ly/wb-precache`;console.warn(t)}}}install(t){return v(t,async()=>{const e=new "
		    "U;this.strategy.plugins.push(e);for(const[e,s]of this.k){const n=this.P.get(s),r=this.K.get(e),i=new Requ"
		    "est(e,{integrity:n,cache:r,credentials:\"same-origin\"});await Promise.all(this.strategy.handleAll({param"
		    "s:{cacheKey:s},request:i,event:t}))}const{updatedURLs:s,notUpdatedURLs:n}=e;return{updatedURLs:s,notUpdat"
		    "edURLs:n}})}activate(t){return v(t,async()=>{const t=await self.caches.open(this.strategy.cacheName),e=aw"
		    "ait t.keys(),s=new Set(this.k.values()),n=[];for(const r of e)s.has(r.url)||(await t.delete(r),n.push(r.u"
		    "rl));return{deletedURLs:n}})}getURLsToCacheKeys(){return this.k}getCachedURLs(){return[...this.k.keys()]}"
		    "getCacheKeyForURL(t){const e=new URL(t,location.href);return this.k.get(e.href)}getIntegrityForCacheKey(t"
		    "){return this.P.get(t)}async matchPrecache(t){const e=t instanceof Request?t.url:t,s=this.getCacheKeyForU"
		    "RL(e);if(s){return(await self.caches.open(this.strategy.cacheName)).match(s)}}createHandlerBoundToURL(t){"
		    "const e=this.getCacheKeyForURL(t);if(!e)throw new s(\"non-precached-url\",{url:t});return s=>(s.request=n"
		    "ew Request(t),s.params=Object.assign({cacheKey:e},s.params),this.strategy.handle(s))}}const N=()=>(E||(E="
		    "new O),E);class j extends r{constructor(t,e){super(({request:s})=>{const n=t.getURLsToCacheKeys();for(con"
		    "st r of function*(t,{ignoreURLParametersMatching:e=[/^utm_/,/^fbclid$/],directoryIndex:s=\"index.html\",c"
		    "leanURLs:n=!0,urlManipulation:r}={}){const i=new URL(t,location.href);i.hash=\"\",yield i.href;const o=fu"
		    "nction(t,e=[]){for(const s of[...t.searchParams.keys()])e.some(t=>t.test(s))&&t.searchParams.delete(s);re"
		    "turn t}(i,e);if(yield o.href,s&&o.pathname.endsWith(\"/\")){const t=new URL(o.href);t.pathname+=s,yield t"
		    ".href}if(n){const t=new URL(o.href);t.pathname+=\".html\",yield t.href}if(r){const t=r({url:i});for(const"
		    " e of t)yield e.href}}(s.url,e)){const e=n.get(r);if(e){return{cacheKey:e,integrity:t.getIntegrityForCach"
		    "eKey(e)}}}},t.strategy)}}t.CacheFirst=class extends m{async L(t,e){let n,r=await e.cacheMatch(t);if(!r)tr"
		    "y{r=await e.fetchAndCachePut(t)}catch(t){t instanceof Error&&(n=t)}if(!r)throw new s(\"no-response\",{url"
		    ":t.url,error:n});return r}},t.NavigationRoute=class extends r{constructor(t,{allowlist:e=[/./],denylist:s"
		    "=[]}={}){super(t=>this.W(t),t),this.M=e,this.S=s}W({url:t,request:e}){if(e&&\"navigate\"!==e.mode)return!"
		    "1;const s=t.pathname+t.search;for(const t of this.S)if(t.test(s))return!1;return!!this.M.some(t=>t.test(s"
		    "))}},t.clientsClaim=function(){self.addEventListener(\"activate\",()=>self.clients.claim())},t.createHand"
		    "lerBoundToURL=function(t){return N().createHandlerBoundToURL(t)},t.precacheAndRoute=function(t,e){!functi"
		    "on(t){N().precache(t)}(t),function(t){const e=N();h(new j(e,t))}(e)},t.registerRoute=h});\n"
		    ""sv;
	}  // namespace contents

	static constexpr entry files[] = {
	    {.name = "/favicon.svg"sv, .contents = contents::file_favicon_svg},
	    {.name = "/index.html"sv, .contents = contents::file_index_html},
	    {.name = "/index.js"sv, .contents = contents::file_index_js},
	    {.name = "/sw.js"sv, .contents = contents::file_sw_js},
	    {.name = "/workbox-19e8203f.js"sv, .contents = contents::file_workbox_19e8203f_js},
	};

	void virtual_filesystem::install_global_data() { set_global(build(files)); }
}  // namespace quick_dra::gui
