function(add_project_test TARGET)
  cmake_parse_arguments(PARSE_ARGV 1 TST "" "" "")
  add_executable(${TARGET}-test ${TST_UNPARSED_ARGUMENTS})
  set_target_properties(${TARGET}-test PROPERTIES FOLDER tests)
  target_compile_options(${TARGET}-test PRIVATE ${QUICK_DRA_ADDITIONAL_COMPILE_FLAGS})
  target_link_options(${TARGET}-test PRIVATE ${QUICK_DRA_ADDITIONAL_LINK_FLAGS})
  target_include_directories(${TARGET}-test
    PRIVATE
    ${CMAKE_CURRENT_SOURCE_DIR}/tests
    ${CMAKE_CURRENT_BINARY_DIR})
endfunction()

function(add_win32_icon TARGET NAME)
  set(RESNAME "${PROJECT_SOURCE_DIR}/data/assets/${NAME}")
  set(RC "${CMAKE_CURRENT_BINARY_DIR}/${TARGET}.dir/icon.rc")
  set(__content "// Copyright (c) 2026 midnightBITS
// This code is licensed under MIT license (see LICENSE for details)
// This file was autogenerated. Do not edit.

LANGUAGE 9, 1

100 ICON \"${RESNAME}\"
")

  file(GENERATE OUTPUT ${RC} CONTENT ${__content})
  target_sources(${TARGET} PRIVATE "${RC}" "${RESNAME}")
endfunction()

# See <https://github.com/lefticus/cppbestpractices/blob/v1.0.0/02-Use_the_Tools_Available.md#compilers>
if(MSVC)
  set(QUICK_DRA_ADDITIONAL_COMPILE_FLAGS
    /D_CRT_SECURE_NO_WARNINGS
    /D_CRT_NONSTDC_NO_WARNINGS
    /utf-8
    /permissive-
    /Zc:__cplusplus
    /W4
    /w14242
    /w14254
    /w14263
    /w14265
    /w14287
    /we4289
    /w14296
    /w14311
    /w14545
    /w14546
    /w14547
    /w14549
    /w14555
    /w14619
    /w14640
    /w14826
    /w14905
    /w14906
    /w14928
    /w14946)

  if(QUICK_DRA_SANITIZE)
    list(APPEND QUICK_DRA_ADDITIONAL_COMPILE_FLAGS
      /fsanitize=address
      /D_DISABLE_VECTOR_ANNOTATION
      /D_DISABLE_STRING_ANNOTATION
    )
  endif()
  if(QUICK_DRA_W_ERROR)
    list(APPEND QUICK_DRA_ADDITIONAL_COMPILE_FLAGS /WX)
  endif()
else()
  set(QUICK_DRA_ADDITIONAL_COMPILE_FLAGS
    -Wall -Wextra
    -Wnon-virtual-dtor
    -Wold-style-cast
    -Wcast-align
    -Wunused
    -Woverloaded-virtual
    -Wpedantic
    -Wconversion
    -Wsign-conversion
    -Wnull-dereference
    -Wdouble-promotion
    -Wformat=2
  )

  if("${CMAKE_CXX_COMPILER_ID}" STREQUAL "Clang")
    list(APPEND QUICK_DRA_ADDITIONAL_COMPILE_FLAGS
      -fcolor-diagnostics
      -Wno-braced-scalar-init

      # -Wlifetime
    )
  else()
    list(APPEND QUICK_DRA_ADDITIONAL_COMPILE_FLAGS
      -fdiagnostics-color
      -Wmisleading-indentation
      -Wduplicated-cond
      -Wduplicated-branches
      -Wlogical-op
      -Wuseless-cast
    )
  endif()

  if(QUICK_DRA_SANITIZE)
    list(APPEND QUICK_DRA_ADDITIONAL_COMPILE_FLAGS
      -fsanitize=address
      -fsanitize=undefined
    )
    list(APPEND QUICK_DRA_ADDITIONAL_LINK_FLAGS
      -fsanitize=address
      -fsanitize=undefined
    )
  endif()
  if(QUICK_DRA_W_ERROR)
    list(APPEND QUICK_DRA_ADDITIONAL_COMPILE_FLAGS -Werror)
  endif()
endif()

if(QUICK_DRA_W_ERROR)
  message(STATUS "Compiling with warnings treated as errors")
endif()
