set(LEGACY_COVERAGE)
set(COVERED_CODE)
set(NOT_COVERED_CODE)

macro(add_legacy_coverage DIRNAME TARGET)
  if (IS_DIRECTORY "${DIRNAME}/src")
    list(APPEND LEGACY_COVERAGE "${TARGET}/src")
    if (IS_DIRECTORY "${DIRNAME}/include")
      list(APPEND LEGACY_COVERAGE "${TARGET}/include")
    endif()
  else()
    list(APPEND LEGACY_COVERAGE "${TARGET}")
  endif()
endmacro()

function(add_to_coverage)
  cmake_parse_arguments(PARSE_ARGV 0 DIR "" "" "")

  set(TARGET_DIR ${CMAKE_CURRENT_SOURCE_DIR})
  cmake_path(RELATIVE_PATH TARGET_DIR BASE_DIRECTORY "${PROJECT_SOURCE_DIR}")

  foreach(DIR ${DIR_UNPARSED_ARGUMENTS})
    if (DIR STREQUAL ".")
      add_legacy_coverage("${CMAKE_CURRENT_SOURCE_DIR}" "${TARGET_DIR}")
      list(APPEND COVERED_CODE "${TARGET_DIR}")
      if (IS_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/tests")
        list(APPEND NOT_COVERED_CODE "${TARGET_DIR}/tests")
      endif()
    elseif (IS_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/${DIR}")
      add_legacy_coverage("${CMAKE_CURRENT_SOURCE_DIR}/${DIR}" "${TARGET_DIR}/${DIR}")
      list(APPEND COVERED_CODE "${TARGET_DIR}/${DIR}")
      if (IS_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/${DIR}/tests")
        list(APPEND NOT_COVERED_CODE "${TARGET_DIR}/${DIR}/tests")
      endif()
    endif()
  endforeach()

  set(LEGACY_COVERAGE ${LEGACY_COVERAGE} PARENT_SCOPE)
  set(COVERED_CODE ${COVERED_CODE} PARENT_SCOPE)
  set(NOT_COVERED_CODE ${NOT_COVERED_CODE} PARENT_SCOPE)
endfunction()

macro(cov_set_parent_scope)
  set(LEGACY_COVERAGE ${LEGACY_COVERAGE} PARENT_SCOPE)
  set(COVERED_CODE ${COVERED_CODE} PARENT_SCOPE)
  set(NOT_COVERED_CODE ${NOT_COVERED_CODE} PARENT_SCOPE)
endmacro()

