name: Clang Tidy

on:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      matrix:
        compiler: [ gcc ]
        build_type: [ Debug ]
        sanitizer: [ false ]
        os: [ ubuntu ]

        include:
          - os: ubuntu
            gcc: true
            ubuntu: true
            home: /home/runner

    permissions:
      contents: read
      pull-requests: read

    env:
      BUILD_TYPE: ${{ matrix.build_type }}
      CONAN_REVISIONS_ENABLED: 1
      FLOW_COMMAND: python ./.flow/flow.py run -D os=${{ matrix.os }} build_type=${{ matrix.build_type }} compiler=${{ matrix.compiler }} sanitizer=${{ matrix.sanitizer }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CONAN_CACHE: ${{ matrix.os }}-${{ matrix.build_type }}-${{ matrix.compiler }}

    runs-on: ubuntu-latest
    name: Check on ${{ matrix.build_type }} with ${{ matrix.compiler }} on ${{ matrix.os }}

    steps:
      - name: Bootstrap
        uses: proj-flow-actions/bootstrap@v1
        with:
          cache-prefix: ${{ matrix.os }}
          python-version: "3.12"
          checkout: true
          submodules: true

      - name: Setup Ubuntu
        if: ${{ matrix.ubuntu }}
        uses: proj-flow-actions/setup-ubuntu@v1
        with:
          compiler: ${{ matrix.compiler }}

      - name: Install ICU
        if: ${{ matrix.ubuntu }}
        run: |
          sudo apt-get install libicu-dev -y

      - name: Setup Conan
        uses: proj-flow-actions/setup-conan@v1
        with:
          user-directory: ${{ matrix.home }}
          cache-prefix: ${{ env.CONAN_CACHE }}

      - name: Configure
        run: ${{ env.FLOW_COMMAND }} -s Conan,CMake

      - name: Build
        run: |
          ${{ env.FLOW_COMMAND }} -s Build
          cmake --preset debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Check
        run: python ./tools/run-tidy.py clang-tidy-18 build/debug
